/**
 * Central registry of React Query keys so pages, hooks and the sync engine
 * invalidate the same caches.
 */
export const queryKeys = Object.freeze({
  users: ['users'],
  deployments: ['deployments'],
  deployment: (id) => ['deployment', id],
  locations: ['locations'],
  categories: ['categories'],
  items: ['items'],
  tasks: ['tasks'],
  templates: ['templates'],
  aresGroups: ['ares-groups'],
  memberships: ['memberships'],
  operationalPeriods: ['operational-periods'],
  positions: ['positions'],
  shifts: ['shifts'],
  assignments: ['assignments'],
  channels: ['channels'],
  commsPlans: ['comms-plans'],
  commsPlanChannels: ['comms-plan-channels'],
  activityLog: ['activity-log'],
  hourEntries: ['hour-entries'],
  feedback: ['feedback'],
  lessons: ['lessons'],
  mapLayers: ['map-layers'],
  assets: ['assets'],
  assetCustody: ['asset-custody'],
  objectives: ['objectives'],
  coverageLog: ['coverage-log'],
  safetyChecklists: ['safety-checklists'],
  namingSchemes: ['naming-schemes'],
  aprsBridges: ['aprs-bridges'],
  aprsLatest: ['aprs-latest'],
  aprsActions: ['aprs-actions'],
  aprsOutbox: ['aprs-outbox'],
  notifications: (email) => (email ? ['notifications', email] : ['notifications']),
});
