-- 019_notification_delivery.sql
-- Notification preferences and delivery beyond the in-app bell (design doc
-- 9.20): web push (self-configuring: VAPID keys are generated by the Edge
-- Function on first use), email and SMS (when the owner configures a
-- provider). A trigger hands every deliverable notification to the
-- `deliver-notification` Edge Function through pg_net; the function
-- authenticates the call with a secret that lives in `app_config`, a table
-- only the service role can read.
--
-- Used only for assignment changes, plan changes, open shifts and
-- coordinator notices. Never a general messaging feature.

CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- ============================================================
-- 1. Server-side configuration (service role only)
-- ============================================================
CREATE TABLE IF NOT EXISTS app_config (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON app_config FROM PUBLIC, anon, authenticated;
INSERT INTO app_config (key, value) VALUES ('hook_secret', encode(gen_random_bytes(24), 'hex')) ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('deliver_url', 'https://rboklyjrdctsbarsbtdj.supabase.co/functions/v1/deliver-notification') ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- 2. Preferences and push subscriptions
-- ============================================================
ALTER TABLE users ADD COLUMN IF NOT EXISTS notification_prefs JSONB NOT NULL DEFAULT '{}'::jsonb;
COMMENT ON COLUMN users.notification_prefs IS '{ push: bool, email: bool, sms: bool } per operator; in-app is always on';

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint     TEXT NOT NULL UNIQUE,
  p256dh       TEXT NOT NULL,
  auth         TEXT NOT NULL,
  user_agent   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  failures     INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx ON push_subscriptions (user_id);
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "push_subscriptions_own" ON push_subscriptions;
CREATE POLICY "push_subscriptions_own" ON push_subscriptions FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- ============================================================
-- 3. Hand deliverable notifications to the Edge Function
-- ============================================================
CREATE OR REPLACE FUNCTION trigger_deliver_notification()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE
  url    TEXT;
  secret TEXT;
BEGIN
  IF NEW.type NOT IN ('assignment_offered', 'assignment_accepted', 'assignment_declined', 'plan_published', 'open_shift', 'info') THEN
    RETURN NEW;
  END IF;
  SELECT value INTO url FROM app_config WHERE key = 'deliver_url';
  SELECT value INTO secret FROM app_config WHERE key = 'hook_secret';
  IF url IS NULL OR secret IS NULL THEN RETURN NEW; END IF;
  PERFORM net.http_post(
    url := url,
    body := jsonb_build_object('type', 'INSERT', 'table', 'notifications', 'record', to_jsonb(NEW)),
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-emcomm-hook', secret),
    timeout_milliseconds := 5000
  );
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- Delivery is best effort; the in-app notification row is the record.
  RETURN NEW;
END;
$$;
REVOKE EXECUTE ON FUNCTION trigger_deliver_notification() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS notifications_deliver ON notifications;
CREATE TRIGGER notifications_deliver
  AFTER INSERT ON notifications
  FOR EACH ROW EXECUTE FUNCTION trigger_deliver_notification();
